# Generated by Django 2.1 on 2019-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('emp_name', models.CharField(db_column='emp_name', max_length=255, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(db_column='emp_id', max_length=255)),
            ],
            options={
                'db_table': 'emp_details',
                'ordering': ['emp_name'],
                'managed': True,
            },
        ),
    ]
